/* Generated by Cython 0.29.24 */

#ifndef __PYX_HAVE__labcamera_tis
#define __PYX_HAVE__labcamera_tis

#include "Python.h"

#ifndef __PYX_HAVE_API__labcamera_tis

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void default_frame_callback(size_t, void *, void *);

#endif /* !__PYX_HAVE_API__labcamera_tis */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initlabcamera_tis(void);
#else
PyMODINIT_FUNC PyInit_labcamera_tis(void);
#endif

#endif /* !__PYX_HAVE__labcamera_tis */
